name: CI to create Tag and Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Tag version (e.g. v0.1.0)'
        required: true
        
  #push:
  #  tags:
  #    - "v*"
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

env:
  build-number: ${GITHUB_RUN_NUMBER}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - run: mvn clean package
      - run: mkdir staging && mv target/calculator-1.0-SNAPSHOT.jar target/calculator-1.0.${{ env.build-number }}.jar && cp target/*.jar staging && cp target/surefire-reports/TEST-*.xml staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
          retention-days: 1
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.event.inputs.version }}"
          title: "Calculator Build ${{ github.run_number }}"
          prerelease: false
          files: |
            staging/*.jar
            staging/TEST-*.xml
            
